version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  frontend:
    build:
      context: ./app/javascript/frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./app/javascript/frontend:/app
    ports:
      - 3001:3000
    depends_on:
      - rails
